version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Contraseña para MySQL
      MYSQL_DATABASE: fac
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: 0150048973/factiuradorservicio:latest  # Imagen de Docker Hub
    container_name: springboot-app
    ports:
      - "9898:9898"
    depends_on:
      db:
        condition: service_healthy  # Espera a que MySQL esté saludable
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fac
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
